services:
  postgres:
    image: postgres:15
    container_name: bookmyevent-db
    environment:
      POSTGRES_DB: bookmyevent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: bookmyevent-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookmyevent
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./frontend
    container_name: bookmyevent-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
